# This file should have been generated by device/*/*/setup-makefiles.sh

PRODUCT_PACKAGES := \
    LiveWallpapersPicker

# Publish that we support the live wallpaper feature.
PRODUCT_COPY_FILES := \
    packages/wallpapers/LivePicker/android.software.live_wallpaper.xml:/system/etc/permissions/android.software.live_wallpaper.xml

# DEVICE_PACKAGE_OVERLAYS

$(call inherit-product, vendor/lge/VM670/VM670-vendor-blobs.mk)
